### PR TITLE
Updates xls2yaml.py, openpyxl, pyyaml

### PR DESCRIPTION
**Pull request by wildsubnet**
Updates to xls2yaml.py to use openpyxl (yaml2xls was already updated).
Updated openpyxl to 3.0.7
Updated pyyaml to 5.4.1
Updated revisions.txt with these changes
Tested under macos 11 and Ubuntu 20.04

### CODE REVIEW

**Review by aburston — CHANGES_REQUESTED** [review]
Could you please remove the commented out changes.  Just remove the old libraries, don't leave comments around to be cleaned up later.

**Comment by wildsubnet** [comment]
Removed 'em.

**Comment by aburston** [comment]
Please check this works with nita-webapp

**Comment by hribeiro-jnpr** [comment]
the webapp fails to export a spreadsheet with this version

**Pull request merged**
